name: net-exporter
namespace: kube-system

userID: 1000
groupID: 1000

port: 8000

dns:
  port: 1053
  label: coredns

timeout: 5s

image:
  registry: quay.io
  repository: giantswarm/net-exporter
  tag: "[[ .Version ]]"

# Control-plane subnets used to generate network policies
# for managed applications.
controlPlaneSubnets: []
