name: net-exporter
serviceType: managed

userID: 1000
groupID: 1000

port: 8000

dns:
  port: 1053
  label: coredns
  namespace: kube-system

timeout: 5s

image:
  registry: docker.io
  name: giantswarm/net-exporter
  tag: "[[ .Version ]]"

kubectl:
  image:
    registry: docker.io
    name: giantswarm/docker-kubectl
    tag: 1.18.8

# Control-plane subnets used to generate network policies
# for managed applications.
controlPlaneSubnets: []
