apiVersion: v1
kind: Service
metadata:
  name: net-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: net-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
spec:
  ports:
    - port: {{ .Values.port }}
  selector:
    app: net-exporter
