version: 2.1
orbs:
  architect: giantswarm/architect@0.8.14

jobs:
  build:
    machine: true
    steps:
    - checkout

    - run:
        name: Get architect binary
        command: |
          wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
          chmod +x ./architect
          ./architect version

    - run: ./architect build

    - run:
        name: Publish chart to CNR using a temporary channel for feature branch deploys
        command: ./architect publish --pipeline=false --channels=wip-${CIRCLE_SHA1}

    - store_test_results:
        path: /tmp/results

    - persist_to_workspace:
        root: .
        paths:
        - ./net-exporter
        - ./architect

  deploy:
    machine: true
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: ./architect deploy

    - run:
        name: Publish to stable
        # Project specific: We deploy net-exporter to control planes too,
        # and draughtsman requires the special version format.
        command: |
          sed -i 's/version:.*/version: 1.0.0-'"${CIRCLE_SHA1}"'/' helm/net-exporter-chart/Chart.yaml
          ./architect publish --pipeline=false --channels=stable

workflows:
  build_e2e:
    jobs:
      - build:
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-net-exporter-to-quay
          image: "quay.io/giantswarm/net-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-net-exporter-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/net-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on git tag.
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
        # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker-legacy:
          name: push-net-exporter-to-aliyun-master-legacy
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/net-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master

      - architect/push-to-app-catalog:
          name: push-net-exporter-to-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "net-exporter"
          requires:
            - push-net-exporter-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - deploy:
          filters:
            branches:
              only: master
          requires:
          - build
          - push-net-exporter-to-aliyun
          - push-net-exporter-to-aliyun-master-legacy
          - push-net-exporter-to-app-catalog
