version: 2.1
orbs:
  architect: giantswarm/architect@0.8.14

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build-net-exporter
          binary: net-exporter
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-net-exporter-to-quay
          image: "quay.io/giantswarm/net-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build-net-exporter
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-net-exporter-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/net-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build-net-exporter
          # Needed to trigger job only on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-net-exporter-to-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "net-exporter"
          requires:
            - push-net-exporter-to-aliyun
            - push-net-exporter-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
