kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: net-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: net-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: net-exporter
  template:
    metadata:
      labels:
        app: net-exporter
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      containers:
      - name: net-exporter
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - "-namespace={{ .Values.namespace }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
        resources:
          # cpu limits removed so that throttling doesn't cause any unwanted
          # side-effects to measurements.
          requests:
            memory: 50Mi
          limits:
            memory: 50Mi
      serviceAccountName: net-exporter
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
