kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: net-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: net-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: net-exporter
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      containers:
      - name: net-exporter
        image: quay.io/giantswarm/net-exporter:[[ .SHA ]]
        args:
        - "-namespace={{ .Values.namespace }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
      serviceAccountName: net-exporter
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
