apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: net-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: net-exporter
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  resourceNames:
  - net-exporter
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: net-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: net-exporter
subjects:
- kind: ServiceAccount
  name: net-exporter
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: net-exporter
  labels:
    app: net-exporter
  apiGroup: rbac.authorization.k8s.io
