apiVersion: v1
kind: Service
metadata:
  name: net-exporter
  namespace: monitoring
  labels:
    app: net-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
spec:
  ports:
    - port: 8000
  selector:
    app: net-exporter
