name: net-exporter
namespace: monitoring

userID: 1000
groupID: 1000

port: 8000

dns:
  port: 1053
  label: coredns

image:
  registry: quay.io
  repository: giantswarm/net-exporter
  tag: [[ .SHA ]]

# Control-plane worker subnets used to generate network policies
# for managed applications.
controlPlaneWorkerSubnets: {{ range $index, $element := .Values.Installation.V1.GiantSwarm.ClusterOperator.ControlPlaneWorkerSubnets }}{{ if $index}} {{end}}{{$element}}{{end}}
