name: net-exporter
namespace: monitoring

userID: 1000
groupID: 1000

port: 8000

dns:
  port: 1053
  label: coredns

timeout: 5s

image:
  registry: quay.io
  repository: giantswarm/net-exporter
  tag: [[ .SHA ]]

namespaceLabeler:
  image:
    name: giantswarm/namespace-labeler

# Control-plane subnets used to generate network policies
# for managed applications.
controlPlaneSubnets: []
